version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    image: dufferdeepu/mean-backend:latest
    container_name: express-api
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production

  frontend:
    image: dufferdeepu/mean-frontend:latest
    container_name: angular-ui
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo-data: